var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/licenses/add/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jdofos._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0w00y_x.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t0~ivc._.js")
R.c("server/chunks/ssr/node_modules_10n6ife._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uvyy1n._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_licenses_add_page_actions_0z87b0j.js")
R.m(56535)
module.exports=R.m(56535).exports
