var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/licenses/[licenseId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c.__qq._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_12ytytb.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t0~ivc._.js")
R.c("server/chunks/ssr/node_modules_10n6ife._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uvyy1n._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_licenses_[licenseId]_page_actions_0mnns.l.js")
R.m(8567)
module.exports=R.m(8567).exports
