var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/how-it-works/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kpfmj7._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_10k9-6-.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t0~ivc._.js")
R.c("server/chunks/ssr/node_modules_10n6ife._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uvyy1n._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_how-it-works_page_actions_0k3t58g.js")
R.m(80732)
module.exports=R.m(80732).exports
